name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

      - name: Run TypeCheck
        run: pnpm typecheck

      - name: Run Test
        run: pnpm test
